sudo: false

language: node_js

node_js:
  - "stable"

services:
  - mongodb

notifications:
  email: false

env:
  TEST_MONGODB_URI: "mongodb://127.0.0.1:27017/mplapiTestTravis"
  global:
    - NODE_ENV=test

before_script:
  - sleep 15

after_success:
  - npm run test:coveralls