version: "3"
services:
    app:
      container_name: Mpl_Api
      restart: always
      build: .
      ports:
        - "3000:3000"
      links:
        - mongo
        - redis
    mongo:
      container_name: mpl_mongo
      image: mongo
      ports:
        - "27017:27017"
    redis:
      container_name: mpl_redis
      image: redis
      ports:
        - "6379:6379"
      command: ["redis-server", "--bind", "redis", "--port", "6379"]